### ISSUE TITLE
Inconsistent term vs. expression for (side-condition)

### ISSUE THREAD

**Issue by MichaelBurge** [racket/redex#166]
Within `pattern`, `define-metafunction`, `reduction-relation`, and `define-relation`, the `(side-condition x)` form evaluates `x` as a Racket expression. However, `define-judgment-form` evaluates it as a redex `term`. 

When changing a definition to use `define-judgment-form`, it's easy to forget an `unquote` which usually causes it to always evaluate as true.

What do you think about changing `define-judgment-form` to evaluate `(side-condition)` as a Racket expression?

**Comment by rfindler** [comment]
We probably should have done that in the beginning, but it is too late to go back now, I'm sorry to say.

(We didn't do it before because define-judgment-form knows how to find metafunctions that appear inside those side-conditions, but it could also just be clever enough to look for `term` directly inside a side-condition. That probably would have been the better choice.)

**Comment by MichaelBurge** [comment]
It's too bad Racket modules don't support a "version", so people can opt-in to backwards-incompatible changes:

Library:
```scheme
(provide (version-at-least 1.5 (rename-out new-define-judgment-form define-judgment-form))
         (version-default      (rename-out old-define-judgment-form define-judgment-form)))
```

User:
```scheme
(require redex/reduction-semantics #:version 1.5)
```

**Comment by rfindler** [comment]
Indeed!
