### ISSUE TITLE
enumerator fails to terminate

### ISSUE THREAD

**Issue by rfindler** [racket/redex#186]
In the program below, the call to `generate-term` never seems to return.

```
#lang racket
(require redex/reduction-semantics)
(define-language L
  (m ::= (e))
  (e ::= (f) 1)
  (f ::= e (e ...)))

(printf "starting\n")
(generate-term L m #:i-th 0)
```

**Comment by maxsnew** [comment]
I don't have time to look at this right now (POPL deadline looming). But it's probably because of the ordering in an infinitary or/e in the implementation which is making it always produce an inductive case. In particular if you swap the order of the cases in `e` or `f` it will work.

There is some code that was supposed to re-order them automatically so that's likely the source of the bug. I can look into it next week.

**Comment by rfindler** [comment]
Oh, right. Bad timing with the POPL deadline! Thanks.

Robby
