### ISSUE TITLE
Feature request: tag-with-names for apply-reduction-relation*

### ISSUE THREAD

**Issue by aartikash** [racket/redex#240]
Noticed that apply-reduction-relation* does not work with tag-with-names. 

It can be useful for beginners  and researchers to see the names of the reductions
being applied when using apply-reduction-relation* with compatible closure and 
context-closure also maybe.

**Comment by rfindler** [comment]
I completely agree with the sentiment behind this request, but I think that taking this specific action would be tricky because there may be many ways to reach a particular irreducible term and indicating that in a simple way doesn't seem possible.

That said, it is thoughts like this that led me to build the [racket/gui](https://docs.racket-lang.org/redex/reference.html#%28part._.G.U.I%29) library. Did you try `traces` or `stepper`?

**Comment by aartikash** [comment]
Yes, redex/GUI does the deed. 

My main concern was that it requires me to 
build it. 

But I see your point regarding the implementation.
