### ISSUE TITLE
alpha-equivalent? requires language name

### ISSUE THREAD

**Issue by schuster** [racket/redex#35]
The prose in the docs imply that Redex's `alpha-equivalent?` should get the language from `default-language`, but in reality it requires a separate `lang` parameter. Either the docs or the code should be fixed (preferably the code - using `default-language` would match `substitute`).

**Comment by rfindler** [comment]
Can you say why you're using `alpha-equivalent?` explicitly? If you need it for comparing two terms, you should be able to just give them the same name in a pattern and that will use alpha equivalence as the "sameness" test.

And yes, I agree the docs are not right. That needs fixing. I don't think that we can change `alpha-equivalent?` at this point because other models are relying on it, tho.

**Comment by schuster** [comment]
I had been using `rackunit` for my testing instead of the built-in Redex forms, just because that's what I'm used to using, and I was writing a simple `check-alpha-equivalent?` predicate. You're right, though, I could use `redex-match` to accomplish the same thing.

**Comment by rfindler** [comment]
You could also define a check that supplied the language you want?

**Comment by schuster** [comment]
Oh, certainly. This bug was just to report that the implementation doesn't match the docs. If the imlementation needs to remain unchanged for backwards compatibility, then a documentation fix is all that's required.

**Comment by rfindler** [comment]
Okay, then I think I'll close this issue. Thanks for the feedback!
