### ISSUE TITLE
Feature Request: Add an expected pattern to `test-judgment-holds`

### ISSUE THREAD

**Issue by florence** [racket/redex#44]
Something like:

```racket
(test-judgment-holds (traverse ((lambda (x) (x x)) (lambda (x) (x x))) any) ;; judgment
                     any ;; output
                     ((lambda (x) (x x)) (lambda (x) (x x)))) ;; expected pattern
```

This would fail in the same cases as

```racket
(test-judgment-holds (traverse ((lambda (x) (x x)) (lambda (x) (x x)))
                               ((lambda (x) (x x)) (lambda (x) (x x)))))
```

But would give a better error message than "judgment of traverse didn't hold". (Ie it would say "Expected pattern <pattern> but found <something-else>.

This would make debugging test failures a little easier when the judgement "held" for some pattern that wasn't the one you expected.

**Comment by rfindler** [comment]
Spencer and I talked and think that a better approach would be to change the way that `test-judgment-holds` works. Roughly, instead of calling `judgment-holds` with its argument it would analyze its argument, find the `O` positions of the judgment and then replace them with `any` and then do an explicit extra `redex-match` afterwards, giving different (more informative) messages when the second phase didn't work out.
