### ISSUE TITLE
side-condition/hidden not supported in define-language

### ISSUE THREAD

**Issue by andmkent** [racket/redex#6]
using side-condition in a language definition works great, but using side-condition/hidden does not (it just treats it like a literal s-expression, I believe)

```racket
#lang racket
(require redex)

(define (unique? l)
  (equal? l (remove-duplicates l)))

(define-language DTR
  [e  ::= x
      (side-condition (λ (x_ ...) e)
                      (unique? (term (x_ ...))))
      ;; (side-condition/hidden (λ (x_ ...) e) ; doesn't work =(
      ;;                        (unique? (term (x_ ...))))
      (e e ...)]
  [x  ::= variable-not-otherwise-mentioned])

(module+ test
  (test-equal (redex-match? DTR e (term (λ (x x) x))) #f)
  (test-equal (redex-match? DTR e (term (λ (x y) (x y)))) #t))
```

**Comment by rfindler** [comment]
That's right: the place where you have written `side-condition/hidden` above is in a pattern and patterns don't generally support that. This isn't a very easy thing to support because it requires some non-trivial cleverness to figure out how to "erase" something from an arbitrary pattern typesetting.

In this particular case, you can just use x_!_1 to get what the side-condition you have above is saying.

I'm going to close this now because I don't have plans to add this functionality and I don't think that the redex issue tracker is really the right place for it anyway. Feel free to continue this conversation elsewhere, however, if you like (with me in email or on the users@racket-lang.org mailing list seem like good places).
