### ISSUE TITLE
Confusing behavior: literals interpreted as variables for binding purposes

### ISSUE THREAD

**Issue by florence** [racket/redex#62]
I don't quite understand what's going on here but a the cyclic binding form in this language seems to break pattern matching.

```
#lang racket
(require redex/reduction-semantics)

(define-language esterel
  ;; If there was only p (ie this rule and pdot were deleted) the test would pass
  (pdotdot ::= pdot p)

  (p ::= nothing)

  (pdot ::= (· p))

  (M (machine pdotdot bindings))
  (bindings (s ...))

  #:binding-forms
  ;; without the following rule the test passes
  (machine pdotdot #:refers-to bindings
           bindings #:refers-to pdotdot))

;; these tests pass
(test-equal (redex-match? esterel M (term (machine nothing ())))
            #t)
(test-equal (redex-match? esterel (machine nothing ()) (term (machine nothing ())))
            #t)

;; this test fails, would expect it to pass
(test-equal (redex-match? esterel (machine pdotdot bindings) (term (machine nothing ())))
            #t)
```

**Comment by paulstansifer** [comment]
I wonder if we should add some sort of debugging option to automatically print out freshening events as they happen; I add a `printf` to do that every time binding is doing something weird.

In this case, the problem is that `nothing`, despite being a literal, it still being interpreted as a binder, and the form `(machine nothing ())` is getting freshened to `(machine nothing«0» ())`. Using `()` or `(nothing)` instead of `nothing` makes the test pass. 

What's going on is specific to variables. Redex has a simple rule: if a variable is referred to (either by `#:refers-to` or `#:exports`), it is a binder. Otherwise it's a reference. There is currently no provision for saying that a particular variable doesn't participate in binding at all. (So using `(nothing)` inside a context where the name `nothing` is bound will also result in bad stuff.)

(I don't think circularity has anything to do with it; I think it's just that if you take away those two rules, `(machine nothing ())` is no longer a binding form, and so doesn't get freshened.)

I'm a little stumped here; I haven't used literals extensively in Redex, and I don't have an intuition for what a Redexy solution to this problem is (I'm thinking of it as a usability problem). Perhaps something as simple as saying that all literals (= names on the RHS of a rule but not on the LHS of any rule) are not variables, and so cannot be freshened?

**Comment by rfindler** [comment]
I think the rule you're describing makes a lot of sense for Redex. Redex is
already explicitly tracking those names (both at compile time and at
runtime) so you should be able to use that information during freshening
(it is in a field of the compiled-lang struct).

**Comment by wilbowma** [comment]
This seems related to #68. Patterns and binding have unexpected behavior together. Consider the following program. Exactly one test fails, can you spot which?

(for the uninitiated, 
`(redex-judgment-holds-chk j [args ...] ...)` is short for 
`(check-true (judgment-holds (j args ...))) ...`)

```racket
#lang racket
(require redex/reduction-semantics)

(define-language λL
  (x ::= variable-not-otherwise-mentioned)
  (e t ::= x (λ (x ...) e))
  #:binding-forms
  (λ (x #:...bind (clauses x (shadow clauses x))) e #:refers-to clauses))

(define-judgment-form λL
  #:mode (out1 I O)
  #:contract (out1 e e)

  [----------
   (out1 e e)])

(define-judgment-form λL
  #:mode (out2 I O)
  #:contract (out2 e e)

  [----------
   (out2 x x)]

  [(out2 e_1 e_2)
   ----------
   (out2 (λ (x ...) e_1) (λ (x ...) e_2))])

(define-judgment-form λL
  #:mode (out3 I I)
  #:contract (out3 e e)

  [(out2 e_1 e_2)
   ----------
   (out3 e_1 e_2)])

(module+ test
  (require redex-chk)
  (redex-judgment-holds-chk
   out1
   [(λ (x) x) (λ (x) x)]
   [(λ (x_1 x_2) x_1) (λ (x_1 x_2) x_1)]
   [(λ (y z) z) (λ (y z) z)]
   [(λ (y z) z) (λ (x_1 x_2) x_2)])

  (redex-judgment-holds-chk
   out2
   [(λ (x) x) (λ (x) x)]
   [(λ (x_1 x_2) x_1) (λ (x_1 x_2) x_1)]
   [(λ (y z) z) (λ (y z) z)]
   [(λ (y z) z) (λ (x_1 x_2) x_2)])

  (redex-judgment-holds-chk
   out3
   [(λ (x) x) (λ (x) x)]
   [(λ (x_1 x_2) x_1) (λ (x_1 x_2) x_1)]
   [(λ (y z) z) (λ (y z) z)]
   [(λ (y z) z) (λ (x_1 x_2) x_2)]))

```

**Comment by rfindler** [comment]
Does it make sense to change the freshening process so that it just ignores literals? (I doubt this will help with @wilbowma 's example, but it probably will with the original symptom and #98)

**Comment by wilbowma** [comment]
That makes a lot of sense. Can we do the dual process: turn literals that are in binding positions in a pattern into a fresh identifier pattern variable? (I think that's what's necessary to solve my example, but not sure it's possible)

**Comment by rfindler** [comment]
I am not sure incompletely get the suggestion. Just to make sure: literals
in the sense I meant it are "symbols" that appear in the grammar that
aren't non-terminals. So:lambda, +, :, etc.

If a literal is used in a pattern, it matches only itself. If it is used in
a term position, it is itself.

Robby

**Comment by wilbowma** [comment]
Ah sorry. I guess I was thinking of literals as arbitrary symbols that don't necessarily appear in the grammar, e.g., `y` and `z` in my above tests. In these cases, I *think* of them as variables, but Redex recognizes them as symbols in a pattern. Hence, `(lambda (x) x)` matches the pattern `(lambda (y) y).

My suggestion was, for these symbols, when they appear in a pattern and in binding position, can they be automatically turned into fresh pattern variables? For example, can we change `(lambda (y z) y)`, when it appears as a pattern instead of a term, into `(lambda (x_1 x_2) x_1)`?

**Comment by iitalics** [comment]
I would to comment that I'm having this same issue, that identifiers that are supposed to be literals are treated as variable and thus incorrectly renamed.

**Comment by iitalics** [comment]
```racket
(define-language L
  [x ::= variable-not-otherwise-mentioned]
  [e ::= x null (cons e e) (λ p e)]
  [p ::= x null (cons p p)]
  #:binding-forms
  (λ p e #:refers-to p)
  (cons p_1 p_2) #:exports (shadow p_1 p_2))

(term (substitute (λ null null) x y) #:lang L)
;; '(λ null«0» null«0»)
```

Is there a workaround yet?

**Comment by rfindler** [comment]
I don't know if the commit I just pushed (19f48d2e94a848dd2bfd533eceb79a0b5f5ed361) solves the original problem in this PR. If @florence / @wilbowma would have a look, that'd be appreciated. (It does make the results for that first program in this thread be what @florence expected.)

**Comment by iitalics** [comment]
This is great, thanks @rfindler.

**Comment by iitalics** [comment]
Actually, looks like it breaks reduction relations.
```racket

(define red
  (reduction-relation L
    (--> e e)))

(traces red '(cons null null))
; α-equal-hash-code: arity mismatch;
;  the expected number of arguments does not match the given number
;   expected: 4
;   given: 3
```

**Comment by rfindler** [comment]
Whoops, sorry. (And there were already tests for those, I just didn't run them :( )

**Comment by rfindler** [comment]
@iitalics I  missed the merge window with this fix. Is it important for this to get into a release, or shall I leave it as is (meaning it will be in a release only in 3 months from now)?

CC @stamourv

**Comment by iitalics** [comment]
Its not a big deal

**Comment by iitalics** [comment]
Thanks, though
