### ISSUE TITLE
Bad indentation of judgment forms in DrRacket

### ISSUE THREAD

**Issue by leafac** [racket/redex#70]
###### Expected behavior

DrRacket's indentation of judgment forms matches the documentation.

###### Current behavior

[The documentation for judgment forms](http://docs.racket-lang.org/redex/The_Redex_Reference.html#%28form._%28%28lib._redex%2Freduction-semantics..rkt%29._define-judgment-form%29%29) contains the following example:

```racket
#lang racket
(require redex)

(define-language nats
  (n ::= z (s n)))

(define-judgment-form nats
  #:mode (sum I I O)
  #:contract (sum n n n)
  [----------- "zero"
   (sum z n n)]
  
  [(sum n_1 n_2 n_3)
   ------------------------- "add1"
   (sum (s n_1) n_2 (s n_3))])
```

DrRacket indents this as (hit <kbd>Cmd+i</kbd> to reproduce):

```racket
#lang racket
(require redex)

(define-language nats
  (n ::= z (s n)))

(define-judgment-form nats
  #:mode (sum I I O)
  #:contract (sum n n n)
  [----------- "zero"
               (sum z n n)]
  
  [(sum n_1 n_2 n_3)
   ------------------------- "add1"
   (sum (s n_1) n_2 (s n_3))])
```

Notice how `(sum z n n)` is misaligned in relation to the `--------` bar above it.

-----

1. Do you agree this is an issue?

2. Is there a configuration/workaround that I'm unaware of?

3. If you agree this is an issue, how can I help fixing it? I'd love to collaborate, but would need a hint on where to start.

-----

Thank you for Redex and DrRacket. They are amazing tools.

**Comment by rfindler** [comment]
I agree and this has annoyed me too. So I changed the way that the gui library's indentation code works to fix this. These are the commits: https://github.com/racket/gui/commit/c3322ca05db5c8e92f644112af8eaa0c4fb3dc28 and https://github.com/racket/gui/commit/9f3635f399e5b4c6e19a12845e377d1c8742961d

This is a change to the behavior of any Racket program's indentation, not just ones that use redex, so this could be confusing and maybe we need to adjust to be guarded by a preference. Lets see if anyone notices :).

As for point 3, this was pretty straightforward since I know the code so I just did it, but there may be other things where it'll make more sense for me to give you some suggestions and I'll be sure to take up kind offers like that going forward!

**Comment by leafac** [comment]
❤️ 
Thanks a lot for that!

The change was simple, indeed, but it would probably have taken me hours to figure out—as I'm not familiar with the code base.

> As for point 3, this was pretty straightforward since I know the code so I just did it, but there may be other things where it'll make more sense for me to give you some suggestions and I'll be sure to take up kind offers like that going forward!

I didn't forget about https://github.com/racket/redex/issues/61, by the way. I'm using Redex more and more, and will get back to that issue when I'm more comfortable with the internals.

**Comment by rfindler** [comment]
No worries! Thanks for you interested in Redex and your support of it!
